name: Push to Org Repo

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Push to Organization Repo
      env:
        ORG_PUSH_TOKEN: ${{ secrets.ORG_PUSH_TOKEN }}
      run: |
        git remote add target https://x-access-token:${ORG_PUSH_TOKEN}@github.com/UsalamaGuard/django-backend.git
        git push target main --force
